name: ci

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: apt-get update
        run: sudo apt-get update
      -
        name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          docker-images: false
          swap-storage: false
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: delusional/sd-rx7900xtx:latest
